server:
    port: 8080

spring:
    datasource:
        username: root
        password: 116139
        url: jdbc:mysql://localhost:3306/mydb
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            # 连接池名
            pool-name: DateHikariCP
            # 最小空闲连接数
            minimum-idle: 5
            # 空闲连接存活最大时间，默认600000（10分钟）
            idle-timeout: 1800000
            # 最大连接数，默认为10
            maximum-pool-size: 10
            # 从连接池返回的连接自动提交
            auto-commit: true
            # 连接最大存活时间，0表示永久存活，默认为 180000（半小时）
            max-lifetime: 1800000
            # 连接超时时间，默认为30000（30秒）
            connection-timeout: 30000
            # 测试连接是否可以使用的查询语句
            connection-test-query: SELECT 1

    jpa:
        database: MySQL
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
        hibernate:
            ddl-auto: update
    redis:
        host: 127.0.0.1
        port: 6379
        password:
    thymeleaf:
        enabled: false
    #RabbitMQ
    rabbitmq:
        host: 127.0.0.1
        username: guest
        password: guest
        virtual-host: /
        port: 5672
        listener:
            simple:
                # 消费者最小数量
                concurrency: 10
                # 消费者最大数量
                max-concurrency: 10
                # 限制消费者每次只处理一条消息
                prefetch: 1
                # 默认启动容器
                auto-startup: true
                # 拒绝时
                default-requeue-rejected: true
                retry:
                    #发布重试，默认false
                    enabled: true
                    #重试时间 默认1000ms
                    initial-interval: 1000ms
                    #重试最大次数 最大3
                    max-attempts: 1
                    #重试最大间隔时间
                    max-interval: 10000ms
                    #重试的时间隔乘数，比如配2，0 第一次等于10s，第二次等于20s，第三次等于40s
                    multiplier: 1


