server:
    port: 8080

spring:
    datasource:
        username: root
        password: 116139
        url: jdbc:mysql://localhost:3306/mydb
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            # 连接池名
            pool-name: DateHikariCP
            # 最小空闲连接数
            minimum-idle: 5
            # 空闲连接存活最大时间，默认600000（10分钟）
            idle-timeout: 1800000
            # 最大连接数，默认为10
            maximum-pool-size: 10
            # 从连接池返回的连接自动提交
            auto-commit: true
            # 连接最大存活时间，0表示永久存活，默认为 180000（半小时）
            max-lifetime: 1800000
            # 连接超时时间，默认为30000（30秒）
            connection-timeout: 30000
            # 测试连接是否可以使用的查询语句
            connection-test-query: SELECT 1

    jpa:
        database: MySQL
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
        hibernate:
            ddl-auto: update
    redis:
        host: 127.0.0.1
        port: 6379
        password:
    thymeleaf:
        enabled: false
