-- MySQL Script generated by MySQL Workbench
-- Sat Oct 15 10:24:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tag` VARCHAR(45) NULL,
  `bedId` INT NOT NULL,
  `gender` BINARY NOT NULL,
  `gid` INT NULL,
  `ID_number` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `student_number` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `building_id` INT NOT NULL,
  `status` BINARY NOT NULL,
  `orderscol` VARCHAR(45) NULL,
  `room_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rooms` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `level` VARCHAR(45) NULL,
  `nums` VARCHAR(45) NOT NULL,
  `remainNums` VARCHAR(45) NOT NULL,
  `lid` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Groups` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gender` BINARY NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buildings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Buildings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Buildings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tag` (
  `tid` INT NOT NULL AUTO_INCREMENT,
  `name` INT NULL,
  PRIMARY KEY (`tid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buildings_Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Buildings_Tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Buildings_Tag` (
  `tag_id` INT NOT NULL,
  `building_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentAdmin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`StudentAdmin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`StudentAdmin` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BuildingAdmin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BuildingAdmin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BuildingAdmin` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `building_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Level` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Level` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `bid` INT NULL,
  `gender` BINARY NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bed` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bed` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rid` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `sid` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentAdmin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`StudentAdmin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`StudentAdmin` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

BEGIN;
/*!40000 ALTER TABLE `Students` DISABLE KEYS */;
INSERT INTO `Students` VALUES (1, 'test', 111111, 0, 1, 0, 1, 510125200105036317, 13348805522, 2201210308, '刘瑞麒s');
/*!40000 ALTER TABLE `Students` ENABLE KEYS */;
COMMIT;