-- MySQL Script generated by MySQL Workbench
-- Sun Oct 16 15:53:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tag` VARCHAR(45) NULL,
  `bed_id` INT NOT NULL,
  `gender` BINARY NOT NULL,
  `group_id` INT NULL,
  `ID_number` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `student_number` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `building_id` INT NOT NULL,
  `status` BINARY NOT NULL,
  `orderscol` VARCHAR(45) NULL,
  `room_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rooms` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `nums` INT NOT NULL,
  `remainNums` INT NOT NULL,
  `building_id` INT NOT NULL,
  `gender` BINARY NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Groups` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gender` BINARY NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buildings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Buildings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Buildings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buildings_Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Buildings_Tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Buildings_Tags` (
  `tag_id` INT NOT NULL,
  `building_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BuildingAdmins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BuildingAdmins` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BuildingAdmins` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `building_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Beds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Beds` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Beds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `room_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `student_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentAdmins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`StudentAdmins` ;

CREATE TABLE IF NOT EXISTS `mydb`.`StudentAdmins` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

BEGIN;
/*!40000 ALTER TABLE `Users` DISABLE KEYS */;
INSERT INTO `Users` VALUES (1, 'test', 111111, 0, 1, 510125200105036317, 13348805522, 2201210308, 'a1', 0);
INSERT INTO `Users` VALUES (2, 'test2', 111111, 0, 1, 510125200105036318, 13348805522, 2201210309, 'a2', 0);
INSERT INTO `Users` VALUES (3, 'test3', 111111, 0, 1, 510125200105036319, 13348805522, 2201210310, 'a3', 0);
/*!40000 ALTER TABLE `Users` ENABLE KEYS */;
COMMIT;

BEGIN;
/*!40000 ALTER TABLE `Buildings` DISABLE KEYS */;
INSERT INTO `Buildings` VALUES (1, '五号楼');
INSERT INTO `Buildings` VALUES (2, '13号楼');
/*!40000 ALTER TABLE `Buildings` ENABLE KEYS */;
COMMIT;


BEGIN;
/*!40000 ALTER TABLE `Rooms` DISABLE KEYS */;
INSERT INTO `Rooms` VALUES (1, '511', 4, 3, 1, 1);
INSERT INTO `Rooms` VALUES (2, '512', 4, 2, 1, 1);
INSERT INTO `Rooms` VALUES (3, '521', 4, 1, 1, 1);
INSERT INTO `Rooms` VALUES (4, '522', 4, 2, 1, 1);
INSERT INTO `Rooms` VALUES (5, '1311', 4, 3, 2, 0);
INSERT INTO `Rooms` VALUES (6, '1312', 4, 1, 2, 0);
INSERT INTO `Rooms` VALUES (7, '1321', 4, 0, 2, 0);
/*!40000 ALTER TABLE `Rooms` ENABLE KEYS */;
COMMIT;