-- MySQL Script generated by MySQL Workbench
-- Sun Oct 16 15:53:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tag` VARCHAR(45) NULL,
  `bed_id` INT NOT NULL,
  `gender` BINARY NOT NULL,
  `group_id` INT NULL,
  `ID_number` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `student_number` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `building_id` INT NOT NULL,
  `status` BINARY NOT NULL,
  `orderscol` VARCHAR(45) NULL,
  `room_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rooms` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `nums` INT NOT NULL,
  `remainNums` INT NOT NULL,
  `building_id` INT NOT NULL,
  `gender` BINARY NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Groups` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gender` BINARY NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buildings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Buildings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Buildings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buildings_Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Buildings_Tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Buildings_Tags` (
  `tag_id` INT NOT NULL,
  `building_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BuildingAdmins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BuildingAdmins` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BuildingAdmins` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `building_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Beds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Beds` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Beds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `room_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `student_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentAdmins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`StudentAdmins` ;

CREATE TABLE IF NOT EXISTS `mydb`.`StudentAdmins` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

BEGIN;
/*!40000 ALTER TABLE `Users` DISABLE KEYS */;
INSERT INTO `Users` VALUES (1, 'test', 111111, 0, 1, 510125200105036317, 13348805522, 2201210308, 'a1', 0);
INSERT INTO `Users` VALUES (2, 'test2', 111111, 0, 1, 510125200105036318, 13348805522, 2201210309, 'a2', 0);
INSERT INTO `Users` VALUES (3, 'test3', 111111, 0, 1, 510125200105036319, 13348805522, 2201210310, 'a3', 0);
INSERT INTO `Users` VALUES (4, 'test4', 111111, 0, 0, 510125200105036320, 13348805522, 2201210311, 'a4', 0);
/*!40000 ALTER TABLE `Users` ENABLE KEYS */;
COMMIT;

BEGIN;
/*!40000 ALTER TABLE `Buildings` DISABLE KEYS */;
INSERT INTO `Buildings` VALUES (1, '五号楼');
INSERT INTO `Buildings` VALUES (2, '13号楼E1');
INSERT INTO `Buildings` VALUES (3, '13号楼E2');
INSERT INTO `Buildings` VALUES (4, '13号楼E3');
INSERT INTO `Buildings` VALUES (5, '14号楼E1');
INSERT INTO `Buildings` VALUES (6, '14号楼E2');
INSERT INTO `Buildings` VALUES (7, '14号楼E3');
INSERT INTO `Buildings` VALUES (8, '9号楼');
/*!40000 ALTER TABLE `Buildings` ENABLE KEYS */;
COMMIT;


BEGIN;
/*!40000 ALTER TABLE `Rooms` DISABLE KEYS */;
INSERT INTO `Rooms` VALUES
                        (1, '511', 4, 4, 1, 0),(2, '512', 4, 4, 1, 0),(3, '513', 4, 4, 1, 0),
                        (4, '514', 4, 4, 1, 0),(5, '515', 4, 4, 1, 0),(6, '516', 4, 4, 1, 0),(7, '517', 4, 4, 1, 0),
                        (8, '518', 4, 4, 1, 0),(9, '519', 4, 4, 1, 0),(10, '520', 4, 4, 1, 1),(11, '521', 4, 4, 1, 1),
                        (12, '522', 4, 4, 1, 1),(13, '523', 4, 4, 1, 1),(14, '524', 4, 4, 1, 1),(15, '525', 4, 4, 1, 1),
                        (16, '526', 4, 4, 1, 1),(17, '527', 4, 4, 1, 1),(18, '528', 4, 4, 1, 1),(19, '529', 4, 4, 1, 1);
/*!40000 ALTER TABLE `Rooms` ENABLE KEYS */;
COMMIT;


BEGIN;
/*!40000 ALTER TABLE `Beds` DISABLE KEYS */;
INSERT INTO `Beds` VALUES

                       (1, 1, '511-1', null, 0),(2, 1, '511-2', null, 0),(3, 1, '511-3', null, 0),(4, 1, '511-4', null, 0),
                       (5, 2, '512-1', null, 0),(6, 2, '512-2', null, 0),(7, 2, '512-3', null, 0),(8, 2, '512-4', null, 0),
                       (9, 3, '513-1', null, 0),(10, 3, '513-2', null, 0),(11, 3, '513-3', null, 0),(12, 3, '513-4', null, 0),
                       (13, 4, '514-1', null, 0),(14, 4, '514-2', null, 0),(15, 4, '514-3', null, 0),(16, 4, '514-4', null, 0),
                       (17, 5, '515-1', null, 0),(18, 5, '515-2', null, 0),(19, 5, '515-3', null, 0),(20, 5, '515-4', null, 0),
                       (21, 6, '516-1', null, 0),(22, 6, '516-2', null, 0),(23, 6, '516-3', null, 0),(24, 6, '516-4', null, 0),
                       (25, 7, '517-1', null, 0),(26, 7, '517-2', null, 0),(27, 7, '517-3', null, 0),(28, 7, '517-4', null, 0),
                       (29, 8, '518-1', null, 0),(30, 8, '518-2', null, 0),(31, 8, '518-3', null, 0),(32, 8, '518-4', null, 0),
                       (33, 9, '519-1', null, 0),(34, 9, '519-2', null, 0),(35, 9, '519-3', null, 0),(36, 9, '519-4', null, 0),
                       (37, 10, '520-1', null, 0),(38, 10, '520-2', null, 0),(39, 10, '520-3', null, 0),(40, 10, '520-4', null, 0),
                       (41, 11, '521-1', null, 0),(42, 11, '521-2', null, 0),(43, 11, '521-3', null, 0),(44, 11, '521-4', null, 0),
                       (45, 12, '522-1', null, 0),(46, 12, '522-2', null, 0),(47, 12, '522-3', null, 0),(48, 12, '522-4', null, 0),
                       (49, 13, '523-1', null, 0),(50, 13, '523-2', null, 0),(51, 13, '523-3', null, 0),(52, 13, '523-4', null, 0),
                       (53, 14, '524-1', null, 0),(54, 14, '524-2', null, 0),(55, 14, '524-3', null, 0),(56, 14, '524-4', null, 0),
                       (57, 15, '525-1', null, 0),(58, 15, '525-2', null, 0),(59, 15, '525-3', null, 0),(60, 15, '525-4', null, 0);
/*!40000 ALTER TABLE `Rooms` ENABLE KEYS */;
COMMIT;