-- MySQL Script generated by MySQL Workbench
-- Sat Oct 15 08:58:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Buildings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Buildings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Buildings` (
  `bid` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Level` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Level` (
  `lid` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `bid` INT NULL,
  `gender` BINARY NULL,
  PRIMARY KEY (`lid`),
  CONSTRAINT `bid`
    FOREIGN KEY (`lid`)
    REFERENCES `mydb`.`Buildings` (`bid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rooms` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rooms` (
  `rid` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `level` VARCHAR(45) NULL,
  `nums` VARCHAR(45) NOT NULL,
  `remainNums` VARCHAR(45) NOT NULL,
  `lid` INT NOT NULL,
  PRIMARY KEY (`rid`),
  INDEX `lid_idx` (`lid` ASC) VISIBLE,
  CONSTRAINT `lid`
    FOREIGN KEY (`lid`)
    REFERENCES `mydb`.`Level` (`lid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bed` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bed` (
  `bedId` INT NOT NULL,
  `rid` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `sid` INT NULL,
  PRIMARY KEY (`bedId`),
  INDEX `rid_idx` (`rid` ASC) VISIBLE,
  INDEX `sid_idx` (`sid` ASC) VISIBLE,
  CONSTRAINT `rid`
    FOREIGN KEY (`rid`)
    REFERENCES `mydb`.`Rooms` (`rid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sid`
    FOREIGN KEY (`sid`)
    REFERENCES `mydb`.`Students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Groups` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Groups` (
  `gid` INT NOT NULL,
  `gender` BINARY NOT NULL,
  PRIMARY KEY (`gid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tag` VARCHAR(45) NULL,
  `bedId` INT NOT NULL,
  `gender` BINARY NOT NULL,
  `gid` INT NULL,
  `ID_number` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `student_number` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `studentscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `gid_idx` (`gid` ASC) VISIBLE,
  INDEX `bedId_idx` (`bedId` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `bedId`
    FOREIGN KEY (`bedId`)
    REFERENCES `mydb`.`Bed` (`bedId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gid`
    FOREIGN KEY (`gid`)
    REFERENCES `mydb`.`Groups` (`gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

BEGIN;
/*!40000 ALTER TABLE `Students` DISABLE KEYS */;
INSERT INTO `Students` VALUES (1, 'test', 111111, 0, 1, 0, 1, 510125200105036317, 13348805522, 2201210308, '刘瑞麒s');
/*!40000 ALTER TABLE `Students` ENABLE KEYS */;
COMMIT;

-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `oid` INT NOT NULL,
  `gid` INT NOT NULL,
  `bid` INT NOT NULL,
  `status` BINARY NOT NULL,
  `orderscol` VARCHAR(45) NULL,
  `rid` INT NULL,
  PRIMARY KEY (`oid`),
  INDEX `gid_idx` (`gid` ASC) VISIBLE,
  INDEX `bid_idx` (`bid` ASC) VISIBLE,
  INDEX `rid_idx` (`rid` ASC) VISIBLE,
  CONSTRAINT `gid`
    FOREIGN KEY (`gid`)
    REFERENCES `mydb`.`Groups` (`gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bid`
    FOREIGN KEY (`bid`)
    REFERENCES `mydb`.`Buildings` (`bid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rid`
    FOREIGN KEY (`rid`)
    REFERENCES `mydb`.`Rooms` (`rid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tag` (
  `tid` INT NOT NULL,
  `name` INT NULL,
  PRIMARY KEY (`tid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buildings_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Buildings_tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Buildings_tag` (
  `tid` INT NOT NULL,
  `bid` INT NOT NULL,
  `btid` INT NOT NULL,
  INDEX `bid_idx` (`bid` ASC) VISIBLE,
  PRIMARY KEY (`btid`),
  CONSTRAINT `tid`
    FOREIGN KEY (`tid`)
    REFERENCES `mydb`.`Tag` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bid`
    FOREIGN KEY (`bid`)
    REFERENCES `mydb`.`Buildings` (`bid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentAdmin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`StudentAdmin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`StudentAdmin` (
  `sadid` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `bid` INT NULL,
  PRIMARY KEY (`sadid`),
  INDEX `bid_idx` (`bid` ASC) VISIBLE,
  CONSTRAINT `bid`
    FOREIGN KEY (`bid`)
    REFERENCES `mydb`.`Buildings` (`bid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BuildingAdmin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BuildingAdmin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BuildingAdmin` (
  `badid` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`badid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
